[build]
  publish = "."

[[redirects]]
  from = "/contact"
  to   = "/contact.html"
  status = 200

[[redirects]]
  from = "/projects"
  to   = "/projects.html"
  status = 200

[[redirects]]
  from = "/articles"
  to   = "/articles.html"
  status = 200

[[redirects]]
  from = "/resume"
  to   = "/resume.html"
  status = 200

[[redirects]]
  from = "/powerbi"
  to   = "/powerbi.html"
  status = 200
